### ISSUE TITLE
Commit 3bfd728 breaks custom plots

### ISSUE THREAD

**Issue by Fredemus** [vizia/vizia#122]
Having a custom plot view and putting it in a `Stack` somehow means it gets clipped in the wrong way:
![image](https://user-images.githubusercontent.com/46689307/162837486-58eb1f1b-3cd6-4a50-8249-e641f16a490b.png)

The only way I've found to fix it is to add `.overflow(Overflow::Visible)` to *every* parent it has, which is less than ideal for a bigger project.

How to reproduce:
Comment in the `HStack` here: https://github.com/Fredemus/va-filter/blob/nih-plug/src/ui.rs#L174-L182, run by writing `cargo run svf_filter svf_gui_bin`.

Completely forgot to file an issue about this because I had vizia locked to a specific commit, sorry!

**Comment by geom3trik** [comment]
As discussed on Discord: The fix for this is to apply `canvas.reset_scissor()` when rendering the plot to an image render target. This call and the rendering of the plot to the image should be wrapped in `canvas.save()` and `canvas.restore()` to preserve the scissor for any other paths rendered in the same `draw()` call.

**Comment by Fredemus** [comment]
That works, thanks!
