### ISSUE TITLE
How long will vizia take to stabilize?

### ISSUE THREAD

**Issue by Anivie** [vizia/vizia#168]
I'm a beginner of rust, but I'm very interested in a GUI framework that supports css. How long will it take for this framework to stabilize?

**Comment by geom3trik** [comment]
I can't really answer that question because we aren't really working to a particular timescale, just whenever people are able to contribute, and the project is constantly evolving. There's still many features that we're hoping to add which will likely result in breaking changes to the API.

However, I am optimistic that we can release a first version, version 0.1, to crates.io in the next couple of months with enough features to create usable applications. This means that any breaking changes will be documented by the version number as per semver.

In fact, depending on your use case, I would encourage you to try it out now and report back any problems you have or features you require. Myself and others have already made some applications with vizia, but if you need something stable and fully-functional right now then vizia is not it just yet. If you would like to try it then I would also encourage you to join our Discord server (link in the readme) for any help migrating since the docs are currently lacking.

**Comment by magnetophon** [comment]
FWIW: vizia v0.1.0  has been released:
https://crates.io/crates/vizia

**Comment by geom3trik** [comment]
> FWIW: vizia v0.1.0 has been released: https://crates.io/crates/vizia

Ah, that is just a placeholder. I probably should have labelled it 0.0.0 but I didn't really know what I was doing. The true version 0.1 should be coming soon though! I want to say in the next couple of months, perhaps sooner.
