### ISSUE TITLE
Data trait derivation requires Data to be in scope

### ISSUE THREAD

**Issue by rhelmot** [vizia/vizia#190]
sticking #[derive(::vizia::prelude::Data)] on a class will fail!

```
error[E0405]: cannot find trait `Data` in this scope
   --> src/assets.rs:109:59
    |
109 |         #[derive(PartialEq, Eq, Hash, Debug, Copy, Clone, ::vizia::prelude::Data)]
    |                                                           ^^^^^^^^^^^^^^^^^^^^^^ not found in this scope
    |
   ::: src/celeste_mod/module.rs:28:1
    |
28  | uuid_cls!(ModuleID);
    | ------------------- in this macro invocation
    |
    = note: this error originates in the derive macro `::vizia::prelude::Data` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider importing one of these items
    |
1   | use crate::Data;
    |
1   | use vizia::state::Data;
    |

```

**Comment by geom3trik** [comment]
There's 2 Data here. One is the derive macro and one is the actual trait. If you add `use vizia::prelude::*` to the top of the file and then just `#[derive(Data)]` to the struct it should work. If you don't want to wild cars import then I'm actually not sure how to disambiguate between the two 🤔 

It's not a bug that the Data trait needs to be in scope because all the derive macro is doing it implementing this trait for the struct.

**Comment by rhelmot** [comment]
I looked into this more carefully and I think I'm just full of shit - I should have specified `$crate::vizia::prelude::Data` instead of `::vizia::prelude::Data`.
