### ISSUE TITLE
Localized error in zh-CN

### ISSUE THREAD

**Issue by ckmro-labs** [vizia/vizia#238]
when I used Localized::new(cx, "hello") in zh-CN，it's not worked in render window。

**Comment by geom3trik** [comment]
> when I used Localized::new(cx, "hello") in zh-CN，it's not worked in render window。

To translate text with fluent you need to add a fluent file to the application which describes the key-value translations. Take a look at the l10n.rs example to see what I mean.

**Comment by ckmro-labs** [comment]
yes. I has added ftl in project.  

`    cx.add_translation(
      ZH_CN,
      include_str!("./resources/zh/i18n.ftl").to_owned(),
    );`
as shown here:
<img width="258" alt="image" src="https://user-images.githubusercontent.com/38417734/192244126-247b845a-9c82-471f-9e80-aae069774794.png">

**Comment by geom3trik** [comment]
Ah it looks like a font issue rather than a translation one. The built-in fonts don't support chinese characters so you'll need to add a font which does. You can add a font with `cx.add_font_mem()` which takes a str name and a byte array for the font. You can get a byte array for a font using the `include_bytes!()` macro. Once you've added the font you'll then need to apply it to the label with the `.font()` modifier, which takes the name you gave it.

**Comment by ckmro-labs** [comment]
greet. thanks.
