### ISSUE TITLE
Question: Comparison with other project

### ISSUE THREAD

**Issue by giannissc** [vizia/vizia#36]
How does that differ (ergonomics, customizability, performance) from:
- tuix
- druid
- iced

Are you doing this is as a hobby or do you intent to use it for a project?
Do you plan on properly supporting modals, popups, dropdown (i.e with mutliple windows)?

From a first look by running the example it look visually beautiful. I will be happy to provide some feedback around ergonomics once I get to try it!

Keep up the good work :)

**Comment by GMAtkinson** [comment]
Hi, thanks for taking a look at vizia and trying the examples. Just to let you know that vizia is currently in the pre-release phase of development and not yet stable, though I do consider it to be usable. Now to answer your questions:

> How does that differ (ergonomics, customizability, performance) from:
> 
> * tuix
> * druid
> * iced

Tuix was my first attempt at a UI library and vizia, which started as an experiment, is the successor. A lot of the code behind tuix is in vizia but the main improvements are a declarative API (inspired by swiftui but not quite as nice because I don't want macros in the API or to use a DSL), and a reactive data system, which means that views only update when the underlying data changes.

Druid is very similar to vizia and I also took a fair amount of inspiration from that project, including the use of lenses. The main difference again is in the API and some subtle differences with how data changes are tracked and lenses are used for binding. The other main difference is how data is updated. Druid goes for mutation through lenses while I'm using an elm-like event-driven approach. For customizability and performance I'm really not sure, sorry. I would need to write similar apps in both frameworks and benchmark them and I don't think there's much point doing that just yet. Oh and the rendering is quit different. Druid uses their own drawing crate which calls into platform libraries but doesn't utilise the GPU so much (though they are actively working on this). Vizia uses OpenGL currently for rendering which makes it fast and portable but potentially lower quality, though I'm happy enough with the results so far.

Iced has a similar model in terms of data updates but as far as I can tell does not have fine-grained reactivity. This means that any changes to data require a complete rebuild of the visual tree. I believe some things are cached to improve performance but I'm not sure of the specifics. The advantage to that approach is that there's less constraints on the data (no traits need to be derived etc). For customizability I think there's a fair amount in both frameworks but again I would have to write an app for proper comparison. The other difference is the rendering. Iced uses wgpu, which is more future proof than OpenGL but also still being developed and doesn't work out-of-box on every system just yet.

> Are you doing this is as a hobby or do you intent to use it for a project? Do you plan on properly supporting modals, popups, dropdown (i.e with mutliple windows)?

A bit of both. It's a hobby but I also intend to use it for a project once I have a good idea I like. I am already using it for a small utility app but nothing special. At the moment I'm quite happy to develop the crate and help others to use it for their projects. I'm also part of a group of people hoping to develop a digital audio workstation (DAW) in Rust and we may use vizia for that. Also, I've been developing this crate (as tuix before) for a few years now and don't intend to stop any time soon.

For modals, popups, and dropdowns with their own windows, it's something I want but I'm relying on winit to do the platform abstraction and it's not yet supported in winit. I'm not a big fan of writing platform code so hopefully it will make its way to winit soon or someone will come along and contribute that part. Multiwindow in general is on the roadmap though and I already have some progress towards that.

> From a first look by running the example it look visually beautiful. I will be happy to provide some feedback around ergonomics once I get to try it!
> 
> Keep up the good work :)

Thank you very much! I'm always happy to hear feedback. Also feel free to join the Discord chat if you like where I am very active. The link is in the readme.

I'm not sure if I answered your question about comparison with other projects so I'll leave this issue open for a while and then maybe when vizia is more stable a more thorough comparison could be done.

**Comment by geom3trik** [comment]
Hi, thanks for taking a look at vizia and trying the examples. Just to let you know that vizia is currently in the pre-release phase of development and not yet stable, though I do consider it to be usable. Now to answer your questions:

> How does that differ (ergonomics, customizability, performance) from:
> 
> * tuix
> * druid
> * iced

Tuix was my first attempt at a UI library and vizia, which started as an experiment, is the successor. A lot of the code behind tuix is in vizia but the main improvements are a declarative API (inspired by swiftui but not quite as nice because I don't want macros in the API or to use a DSL), and a reactive data system, which means that views only update when the underlying data changes.

Druid is very similar to vizia and I also took a fair amount of inspiration from that project, including the use of lenses. The main difference again is in the API and some subtle differences with how data changes are tracked and lenses are used for binding. The other main difference is how data is updated. Druid goes for mutation through lenses while I'm using an elm-like event-driven approach. For customizability and performance I'm really not sure, sorry. I would need to write similar apps in both frameworks and benchmark them and I don't think there's much point doing that just yet. Oh and the rendering is quit different. Druid uses their own drawing crate which calls into platform libraries but doesn't utilise the GPU so much (though they are actively working on this). Vizia uses OpenGL currently for rendering which makes it fast and portable but potentially lower quality, though I'm happy enough with the results so far.

Iced has a similar model in terms of data updates but as far as I can tell does not have fine-grained reactivity. This means that any changes to data require a complete rebuild of the visual tree. I believe some things are cached to improve performance but I'm not sure of the specifics. The advantage to that approach is that there's less constraints on the data (no traits need to be derived etc). For customizability I think there's a fair amount in both frameworks but again I would have to write an app for proper comparison. The other difference is the rendering. Iced uses wgpu, which is more future proof than OpenGL but also still being developed and doesn't work out-of-box on every system just yet.

> Are you doing this is as a hobby or do you intent to use it for a project? Do you plan on properly supporting modals, popups, dropdown (i.e with mutliple windows)?

A bit of both. It's a hobby but I also intend to use it for a project once I have a good idea I like. I am already using it for a small utility app but nothing special. At the moment I'm quite happy to develop the crate and help others to use it for their projects. I'm also part of a group of people hoping to develop a digital audio workstation (DAW) in Rust and we may use vizia for that. Also, I've been developing this crate (as tuix before) for a few years now and don't intend to stop any time soon.

For modals, popups, and dropdowns with their own windows, it's something I want but I'm relying on winit to do the platform abstraction and it's not yet supported in winit. I'm not a big fan of writing platform code so hopefully it will make its way to winit soon or someone will come along and contribute that part. Multiwindow in general is on the roadmap though and I already have some progress towards that.

> From a first look by running the example it look visually beautiful. I will be happy to provide some feedback around ergonomics once I get to try it!
> 
> Keep up the good work :)

Thank you very much! I'm always happy to hear feedback. Also feel free to join the Discord chat if you like where I am very active. The link is in the readme.

I'm not sure if I answered your question about comparison with other projects so I'll leave this issue open for a while and then maybe when vizia is more stable a more thorough comparison could be done.

**Comment by magnetophon** [comment]
Thanks for the informative writeup.
Maybe you should link or copy/paste it in the readme?

**Comment by geom3trik** [comment]
> Thanks for the informative writeup. Maybe you should link or copy/paste it in the readme?

That's not a bad idea. I think I'll do something more thorough once vizia hits 0.1 and it becomes more clear what features are available in comparison to other crates. I also need to spend some time researching these other options so I'm not just spouting rubbish. The above writeup was based on a very general understanding of how these other crates work and I could very well be wrong on some of the details.
