### ISSUE TITLE
Focus order keyboard navigation

### ISSUE THREAD

**Issue by geom3trik** [vizia/vizia#55]

**Comment by rhelmot** [comment]
Things necessary to close this:

- visual indicators for which element is focused. I think we should add the `outline` property from html, add a style for it on `*:focus`, and override it on any element which has custom focus.
- elements need to respond to spacebar like a click. I think we should add a `handle.press_or_space(action)`.

**Comment by geom3trik** [comment]
Good idea for the `outline` style property, I'll go ahead and add that.

I think the key used to trigger an action should be customizable and is dependent on the control. Not sure if this should be specific to the control itself or as an `Enviroment` variable which can be configured for all controls.

**Comment by 0HyperCube** [comment]
Other things necessary for good keyboard navigation:
- [ ] Popups (such as the modal example) should lock focus to within them so you can't tab outside until they are closed.
- [ ] Dropdowns should allow selection via the up and down arrow keys and enter/space like html `<select>` - this requires changing how dropdowns are done because we currently have no concept of a selected row.
- [ ] Menus should be also be navagatable with the arrow keys with left and right opening or closing submenus or navigating to the next or previous menu stack.
- [ ] Arrow key support for changing knobs
- [ ] Arrow key support for changing sliders
- [ ] A general way of making stacks or lists navigatable via arrow keys.

**Comment by geom3trik** [comment]
This is a very useful list of requirements, thank you. I think if we sort out keyboard navigation within lists then that can be used for both menus and dropdowns.
